// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TreeStructureAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nodeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("nodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Depth = 0,
                            Name = "Root"
                        },
                        new
                        {
                            Id = 2,
                            Depth = 1,
                            Name = "A1",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Depth = 1,
                            Name = "A2",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Depth = 2,
                            Name = "B1",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 5,
                            Depth = 2,
                            Name = "B2",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 6,
                            Depth = 3,
                            Name = "C1",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 7,
                            Depth = 3,
                            Name = "C2",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 8,
                            Depth = 3,
                            Name = "C3",
                            ParentId = 4
                        });
                });

            modelBuilder.Entity("Entities.Node", b =>
                {
                    b.HasOne("Entities.Node", "ParentNode")
                        .WithMany("ChildrenNodes")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("Entities.Node", b =>
                {
                    b.Navigation("ChildrenNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
